import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'X Clone',
  description: 'Generated by sjcrippa'
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
